const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getBookings: () => ipcRenderer.invoke('bookings:getAll'),
  saveBooking: (booking) => ipcRenderer.invoke('bookings:save', booking),
  deleteBooking: (id) => ipcRenderer.invoke('bookings:delete', id),
  getExpenses: () => ipcRenderer.invoke('expenses:getAll'),
  saveExpense: (expense) => ipcRenderer.invoke('expenses:save', expense),
  deleteExpense: (id) => ipcRenderer.invoke('expenses:delete', id),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings) => ipcRenderer.invoke('settings:save', settings),
  listPrinters: () => ipcRenderer.invoke('printers:list'),
  printContent: (options) => ipcRenderer.invoke('print:content', options),
  exportPDF: (options) => ipcRenderer.invoke('print:toPDF', options),
  exportExcel: (payload) => ipcRenderer.invoke('export:excel', payload),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  replaceAllBookings: (bookings) => ipcRenderer.invoke('bookings:replaceAll', bookings),
  exportBackup: (jsonString) => ipcRenderer.invoke('backup:export', jsonString),
  importBackup: () => ipcRenderer.invoke('backup:import'),
  getAutoBackupInfo: () => ipcRenderer.invoke('backup:autoInfo'),
  openAutoBackupFolder: () => ipcRenderer.invoke('backup:openAutoFolder'),
  getRemoteInfo: () => ipcRenderer.invoke('remote:getInfo'),
  setRemoteEnabled: (enabled) => ipcRenderer.invoke('remote:setEnabled', enabled),
  setPublicEnabled: (enabled) => ipcRenderer.invoke('remote:setPublicEnabled', enabled),
  regenerateRemoteToken: () => ipcRenderer.invoke('remote:regenerateToken'),
  regenerateNtfyTopic: () => ipcRenderer.invoke('remote:regenerateNtfyTopic'),
  testRemoteConnectivity: () => ipcRenderer.invoke('remote:testConnectivity'),
  onRemotePublicReady: (callback) => ipcRenderer.on('remote:publicReady', (event, url) => callback(url)),
  setAllowBookingRequests: (enabled) => ipcRenderer.invoke('remote:setAllowBookingRequests', enabled),
  getPendingBookings: () => ipcRenderer.invoke('pending:getAll'),
  deletePendingBooking: (id) => ipcRenderer.invoke('pending:delete', id),
  onPendingNew: (callback) => ipcRenderer.on('pending:new', (event, pending) => callback(pending))
});
